In [1]:
import cv2
import numpy as np

In [2]:
# maximun number of iterations is set to 30 for termination of subpixel finding
#0.001 is precision of point
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

#creating an empty array of size 6*9. So that later we can assign it as world coordinate points
objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:6,0:9].T.reshape(-1,2)
#mgrid makes it as points x ranging from 0to5 and y ranging from 0to8
#objp[:, :2] means that we are assigning the values obtained from RHS to first 2 columns rows are not manipulated because
#shape of RHS is 54x2 and LHS is 54x3

objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = ["left01.jpg", "left02.jpg", "left03.jpg", "left04.jpg", "left05.jpg", "left06.jpg", "left07.jpg", 
          "left08.jpg", "left09.jpg", "left11.jpg", "left12.jpg", "left13.jpg", "left14.jpg"]

for image in images:
    img = cv2.imread(image)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    ret, corners = cv2.findChessboardCorners(gray, (6,9), None)
    #found corners
    
    if(ret==True):
        objpoints.append(objp)
        
        corners2 = cv2.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
        #to get acurate camera values we need to get exact location of edge pixel
        #print(corners2)
        imgpoints.append(corners)
        
        # Draw and display the corners
        cv2.drawChessboardCorners(img, (6,9), corners2, ret)
        cv2.imshow('img', img)
        cv2.waitKey(0)
    else:
        print("NO")


cv2.destroyAllWindows()

In [3]:
#reversing the shape of gray image because we are supposed to pass image shape as w, h(by default it will be stored ad h, w)
ret, camera_mat, dis_coeff, rot_mat, trans_mat = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

# print(ret)
print(dis_coeff)
print(camera_mat)
print(rot_mat)
print(trans_mat)
#rot and trans are given in form of vector for all the given images. Direction of vector specifies axis of rotation and 
#magnitude specifes angle of rotation

[[-0.26509006 -0.0467439   0.00183301 -0.00031471  0.25231586]]
[[536.07343019   0.         342.37038791]
 [  0.         536.01634475 235.53685635]
 [  0.           0.           1.        ]]
[array([[-0.08398744],
       [ 0.34802802],
       [-1.54244125]]), array([[-0.22584693],
       [ 1.01551139],
       [-2.79470629]]), array([[-0.34698247],
       [-0.06738503],
       [-1.20088995]]), array([[-0.27527336],
       [ 0.10123358],
       [-1.56296566]]), array([[-0.47359526],
       [ 0.08970848],
       [-0.22605978]]), array([[0.0652592 ],
       [0.44701844],
       [0.10800011]]), array([[-0.1014161 ],
       [ 0.32034834],
       [ 0.3147293 ]]), array([[-0.35339067],
       [ 0.24071879],
       [ 0.20970029]]), array([[ 0.48287252],
       [-0.17036999],
       [-1.40740334]]), array([[ 0.05280146],
       [-0.60171822],
       [-0.18453822]]), array([[-0.37463359],
       [ 0.06982834],
       [-0.01937108]]), array([[ 0.49542331],
       [ 0.11948823],
       [-0.29675962

In [8]:
objp = np.zeros((6*9,3), np.float32)
# objp[:,:2] = np.mgrid[0:6,0:9].T.reshape(-1,2)
print(np.mgrid[0:6,0:9])
print(np.mgrid[0:6,0:9].T)#transpose happens in a way that 1st col in 1st sub array and 1st col in 2nd sub array changes
# print(np.mgrid[0:6,0:9].T.reshape(-1,2))
objp[:,:2] = np.mgrid[0:6,0:9].T.reshape(-1,2)#this will pass the array to 0, 1 positions in objp
# print(objp[:, :])

[[[0 0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3 3 3]
  [4 4 4 4 4 4 4 4 4]
  [5 5 5 5 5 5 5 5 5]]

 [[0 1 2 3 4 5 6 7 8]
  [0 1 2 3 4 5 6 7 8]
  [0 1 2 3 4 5 6 7 8]
  [0 1 2 3 4 5 6 7 8]
  [0 1 2 3 4 5 6 7 8]
  [0 1 2 3 4 5 6 7 8]]]
[[[0 0]
  [1 0]
  [2 0]
  [3 0]
  [4 0]
  [5 0]]

 [[0 1]
  [1 1]
  [2 1]
  [3 1]
  [4 1]
  [5 1]]

 [[0 2]
  [1 2]
  [2 2]
  [3 2]
  [4 2]
  [5 2]]

 [[0 3]
  [1 3]
  [2 3]
  [3 3]
  [4 3]
  [5 3]]

 [[0 4]
  [1 4]
  [2 4]
  [3 4]
  [4 4]
  [5 4]]

 [[0 5]
  [1 5]
  [2 5]
  [3 5]
  [4 5]
  [5 5]]

 [[0 6]
  [1 6]
  [2 6]
  [3 6]
  [4 6]
  [5 6]]

 [[0 7]
  [1 7]
  [2 7]
  [3 7]
  [4 7]
  [5 7]]

 [[0 8]
  [1 8]
  [2 8]
  [3 8]
  [4 8]
  [5 8]]]


In [5]:
a = np.mgrid[0:3, 0:2]
a

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[0, 1],
        [0, 1],
        [0, 1]]])